### ISSUE TITLE
Automate adding new user profiles

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kubeflow-profiles-operator#71]
Work items are tracked in: https://warthogs.atlassian.net/browse/KF-718
Initial action branch: https://github.com/canonical/kubeflow-profiles-operator/tree/kf-792-ceate-user-profile-action
Expanded action branch: https://github.com/canonical/kubeflow-profiles-operator/tree/kf-794-expanded-user-creation-action

## Design
Implement a Juju action that adds a user profile to an authenticated user. Action creates the profile and applies necessary configurations (mlflow and minio PodDefaults, and seldon-mlflow secret) to the profile's namespace.

## Testing

- Setup MicroK8S cluster and Juju controller:
```
microk8s enable dns storage metallb:"10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111"
juju bootstrap microk8s uk8s
juju add-model kubeflow
```
- Deploy kubeflow profiles charm
```
juju deploy ./*.charm --resource kfam-image=$(yq eval ".resources.kfam-image.upstream-source" metadata.yaml) --resource profile-image=$(yq eval ".resources.profile-image.upstream-source" metadata.yaml) --trust
```
- set the feature flag `export JUJU_FEATURES=actions-v2`
- in a terminal run:

```
juju run kubeflow-profiles-operator/0 create-profile authusername=<authenticated_username> profilename=<new_name> 
```
- to include resource quota in profile creation run:
```
# first save the resource quota in a variable
QUOTA=$(cat <<END
{
  "hard": {
    "cpu": "2",
    "memory": "2Gi",
    "requests.nvidia.com/gpu": "1",
    "persistentvolumeclaims": "1",
    "requests.storage": "5Gi"
  }
}
END
)

juju run kubeflow-profiles/0 create-profile authusername="admin" profilename="myname" resourcequota="$QUOTA" --string-args
```
- Check that profile was created, run `microk8s  kubectl get profiles -n kubeflow`
- Check that PodDefaults are applied to namespace using `microk8s kubectl get PodDefaults -n <profile_name>`
- [Conditional] Check that seldon secret is copied to the profile's namespace **in case it existed in the Kubeflow namespace**

## TODOs

- [x] wait for profile namespace to be created before applying configuration
- [x] apply seldon-mlflow secret
- [x] implement handler for initialize-user action
- [x] unit testing
- [x] integration testing
- [ ] update Readme
